### PR TITLE
test: add failing test to handle case with malformed html

### PR DESCRIPTION
**Pull request by sergeyt**
it would be nice to fix this test case

### CODE REVIEW

**Comment by ericnorris** [comment]
Hey @sergeyt! It's not very clear to me what exactly the issue is that you're trying to fix, but I'd guess that it's something to do with the fact that this library might strip more text than you'd expect if it's given invalid HTML.

I don't think that this is an issue because this library is **not** an HTML parser - it's a state machine to strip tags, and it will process the text you give it strictly. If you want to parse HTML (including malformed HTML), you will probably be better off with an HTML parsing library (e.g. `htmlparser2` as you have found).

**Comment by sergeyt** [comment]
Hey @ericnorris if you run this test you can get an idea that there is a difference and it is quite significant. Let me inline this diff here:

```
Error: expect(received).toEqual(expected) // deep equality

- Expected  - 12
+ Received  +  0

  {{first_name}},

  Your recent LinkedIn post on {{! POST TOPIC }} made me want to
  reach out. I’d love to know how you’re addressing
- Generating more leads that fit your ICP.
-
- and what your thoughts are on
- Use more relevant account-level insights to know which companies that fit your ICP are ready to
-     buy now, not later.. If you’re interested in talking more, I’m free
- Tuesday @ 11:00am
- and
- Thursday @ 1:00pm
- for a quick call.
-
- Thanks,
- {{sender.first_name}}
```

There is missing a large block of text that can be extracted by htmlparser2. To narrow down the issue in this case the stiptags library at current state cannot skip invalid html attributes. To me it should be quick fix that is why I decided to share my debugging trace.

p.s. htmlparser2 is also a state machine with just more code 😄

**Comment by ericnorris** [comment]
Understood, but I don't think that this is a problem - `striptags` will strip invalid HTML aggressively because it isn't a parser.

> p.s. htmlparser2 is also a state machine with just more code 😄

Of course, I didn't say that `htmlparser2` is not a state machine, but I did say that `striptags` is not a parser. It is a state machine to strip tags, and that's all it will do. It doesn't understand HTML past "`<` means the start of a tag", roughly speaking. Parsing HTML involves handling all sorts of edge cases that are better left to an actual parsing library.

For what it's worth, I wrote this library to be a Javascript equivalent of PHP's `strip_tags`, and you can see that PHP does the exact same thing (https://3v4l.org/l33j1#v8.1.1):

```
echo strip_tags($bad_html);
```

```
{{first_name}},
Your recent LinkedIn post on {{! POST TOPIC }} made me want to
reach out. I’d love to know how you’re addressing
```

**Comment by sergeyt** [comment]
@ericnorris got it, just tried to suggest making this library covering more cases so it can be used in more applications. You can consider keeping compatibility with PHP, but having an optional mode (forgiving mode) to produce same result like htmlparser2. To me PHP behavior is a bug since the whole text block is omitted.

**Pull request closed without merging**
